adds `addSignWithDhtData` so user can sign a transaction w/ single dht tuple
ergoplatform/ergo-playgrounds pull request #24
Opened 2022-02-13 04:39 UTC by techiejd

It's used like this: https://scastie.scala-lang.org/x6bwPi9eRDiqX4m1cEJsNg

It works locally. Ideally, there'd be an available test suite but I'm having trouble locating it. So, if someone could take a look at this PR and explain if there are other steps.

Thanks.

2022-02-13 06:01 UTC, greenhat requested changes
Thank you for your contribution! Please check my suggestions.

2022-02-13 06:01 UTC, greenhat commented on playground-env/src/main/scala/org/ergoplatform/playgroundenv/models/DummyWalletImpl.scala
> +  override def signWithDHTData(proveDHTuple: ProveDHTuple, tx: UnsignedErgoLikeTransaction): ErgoLikeTransaction = {
I'd rather add `Wallet.withDHSecret(proveDHTuple: ProveDHTuple): Wallet` and stored it in a private property (like `masterKey`) and use it in `sign` instead of adding `signWithDHTData`. This way you can have a wallet with multiple secrets.

2022-02-13 15:09 UTC, techiejd commented on playground-env/src/main/scala/org/ergoplatform/playgroundenv/models/DummyWalletImpl.scala
> +  override def signWithDHTData(proveDHTuple: ProveDHTuple, tx: UnsignedErgoLikeTransaction): ErgoLikeTransaction = {
Good idea, changed!

2022-02-14 05:53 UTC, greenhat requested changes
Thank you! Looking great! Please, make Ci green (formatting).

2022-02-14 17:48 UTC, greenhat approved these changes
Great! Thank you!

2022-02-14 17:48 UTC, merged